import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import PageHeading from "./components/layout/PageHeading";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-gradient-to-br from-gray-950 to-gray-900 text-white flex flex-col">
          {/* Header */}
          <Header />
          {/* Main Content */}
          <main className="flex flex-col items-center justify-center p-6">
            <PageHeading />
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
